### ISSUE TITLE
Cloud Credits Request: Linkerd

### ISSUE THREAD

**Issue by jeefy** [cncf/credits#8]
**Copying over from Service Desk** -- Original Submitter: @olix0r

ASP filing from email: 

“We've been getting reports about bugs that are specific to AWS/EKS and it's difficult for us to reproduce these issues without AWS credits. We've been able to backchannel some of these issues through friends who work there, but I'm curious if there's any AWS/CNCF relationship we could leverage to help ensure Linkerd works well for Amazon customers.”

---

Oliver Gould 
February 25, 2022, 3:25 PM

Thanks. I expect we’ll need 1 EKS cluster for testing, which is quoted at $73/month and $876 for a yearly reservation.

https://calculator.aws/#/estimate?id=fe1429968ab406d62428a5cc45503352c2364243

It’s unclear to me what this reservation includes, exactly (i.e. I’m unsure if worker nodes require additional reservations?)

In general it would be good to retain this cluster so we could include this in pre-release integration testing, but we’ll need it at the very least for ~two months to work through some recently reported issues.

**Comment by hh** [comment]
/assign @BobyMCbobs 
Can you create an LinkerD AWS sub-org, and let's coordinate with Oliver on account details.

**Comment by arieljatib** [comment]
@BobyMCbobs ping ^^

**Comment by BobyMCbobs** [comment]
Hi folks :wave: 

We're getting ready to provision an account with access and require the email address of those to use it, please provide the emails for the users that we'll create for you.

cc @jeefy @olix0r

**Comment by BobyMCbobs** [comment]
Hey folks,

I've made a PR for adding the Linkerd AWS account base configurations.

#17 

I require a few pieces of information before the PR can be made ready

- [ ] what AWS services need to be accessed? (IAM policy)
  - EKS
- [ ] what are the emails of who will access the account? (IAM users)
- [ ] requested budget is $73/mo USD?

Depends on: #15

cc @jeefy @olix0r

**Comment by olix0r** [comment]
> what AWS services need to be accessed? (IAM policy)

As far as I know, we only need access to EKS

> what are the emails of who will access the account? (IAM users)

The [active maintainers https://github.com/linkerd/linkerd2/blob/e5633a2996c56d017eb7deaacda3403e149dc86b/MAINTAINERS.md]:
* Oliver Gould [ver@buoyant.io](mailto:ver@buoyant.io) @olix0r
* Alejandro Pedraza [alejandro@buoyant.io](mailto:alejandro@buoyant.io) @alpeb
* Alex Leong [alex@buoyant.io](mailto:alex@buoyant.io) @adleong
* Eliza Weisman [eliza@buoyant.io](mailto:eliza@buoyant.io) @hawkw
* Kevin Leimkuhler [kevinl@buoyant.io](mailto:kevinl@buoyant.io) @kleimkuhler
* Matei David [matei@buoyant.io](mailto:matei@buoyant.io) @mateiidavid

> requested budget is $73/mo USD?

I don't have enough experience with EKS to know whether this estimate is accurate. What happens if we go over budget? How hard is it to adjust this post-hoc?

**Comment by BobyMCbobs** [comment]
@olix0r, I want to match up your required permissions for creating and managing the EKS cluster.
Do you know how it will be provisioned?
if through Terraform, can you see what resource API will be used?

**Comment by olix0r** [comment]
@BobyMCbobs Yeah, I expect we'll want to use terraform, but we don't have anything setup for this yet--it's a bit of a chicken-and-egg problem... I'll try to get someone on the team to spend some time on this, but I think we're all fairly new when it comes to using AWS/EKS.

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs Yeah, I expect we'll want to use terraform, but we don't have anything setup for this yet--it's a bit of a chicken-and-egg problem... I'll try to get someone on the team to spend some time on this, but I think we're all fairly new when it comes to using AWS/EKS.

@olix0r, would you want to just have an EKS cluster to access and not manage it or it is to be more managed? (teared down and created, etc...)

**Comment by olix0r** [comment]
@BobyMCbobs we'll want to be able to tear it down/recreate/upgrade it.

**Comment by BobyMCbobs** [comment]
Update!

The account has been provisioned and made read for use.
The last thing I am to figure out is providing the folks listed (via emails here https://github.com/cncf/credits/issues/8#issuecomment-1195729847) with their credentials.

cc @olix0r @jeefy @hh @riaankl

**Comment by kleimkuhler** [comment]
@BobyMCbobs thanks for your work on this so far. I'm one of the Linkerd maintainers listed above and I'm wondering what needs to happen for this issue to be closed? I'm hoping to perform some tests in EKS and having these credits for creating a cluster would be helpful.

I see you mentioned

> The account has been provisioned and made read for use.

What do you need from us in order to provide the credentials from logging in and managing a cluster?
